### ISSUE TITLE
Ревью интерфейса FieldManager

### ISSUE THREAD

**Issue by Vovan-S** [Upgrowth-project/Upgrowth-console#1]
https://github.com/Upgrowth-project/Upgrowth-console/tree/project-restruction/Core/src/main/kotlin/ru/honfate/upgrowth/core/api/field

**Comment by EduardLimonov** [comment]
Well-balanced interfaces, a few laugh, a few meaning

**Comment by EduardLimonov** [comment]
Я внес в дата классы следующие изменения:
- Property.targetAnimalReference: Int?
- Player.hand, .animals -> MutableCollection<...>
- Animal.properties -> MutableCollection
- Location.animals -> MutableCollection; добавил поле goodsFunctions: GoodsFunctions (созданный по соседству интерфейс)
- Добавлен data class FieldManagerInitializer для инициализации FieldManager и Field
- Кое-где поменял val на var

deleteProperty должно передавать еще и животное (изменил интерфейс), чье свойство удаляется, или id свойства должно быть уникальным (одинаковые свойства разных животных имеют разные id). На данный момент, насколько я представляю себе, семантика id -- идентификатор класса свойств -- синоним названия свойства, используемый в описании правил. 
Также изменил интерфейс giveCards (number: Number -> Int).
Не понял прикола refresh, всё остальное реализовал.

**Comment by Vovan-S** [comment]
> Не понял прикола refresh, всё остальное реализовал.

Классы предполагались read-only, в течении работы данные в них могут измениться, кроме id. Предполагалось, что метод будет находить сущность с таким же id и возвращать актуальную (освеженную) версию
